### ISSUE TITLE
Apply hint never returns

### ISSUE THREAD

**Issue by nmichael44** [haskell/haskell-language-server#678]
First, let me thank you for all your efforts in building a Haskell IDE.  It is something that the language desperately needs.

### Your environment
```
haskell-language-server version: 0.7.0.0 (GHC: 8.8.4) (PATH: /home/neo/.config/Code/User/globalStorage/haskell.haskell/haskell-language-server-0.7.0-linux-8.8.4) (GIT hash: 6a692de3308c06d8eb7bdf0f7b8a35b6e9a92610)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.5.1
ghc:		8.8.4
```
Which lsp-client do you use:
```VS Code```
Describe your project (alternative: link to the project):
```Stack project using package.yaml```
Contents of `hie.yaml`:
```I don't have this file at all so I am picking up the default behavior.```

### Steps to reproduce
Whenever VS-code highlights a piece of code with a blue squiggly line like suggesting some hint/refactoring, if I click on quick fix, the hint never happens and I get a small window on the bottom right of the screen saying "applying hint" (see attached image) but it never gets applied.  Eventually I just have to hit cancel to get rid of the window.  This happens for every hint.

![image](https://user-images.githubusercontent.com/55693060/102399349-2f64d800-3fe9-11eb-8a75-4dd16aac9d19.png)

**Comment by jneira** [comment]
Thank you for trying it and report the issue.
I think the issue is similar to #646: an underlying error (that may be different) makes the pop up never finishes, instead closing it with a error message.
The error will be likely related with #591 so the workaround provided there may help you to make hlint work.
I am gonna close this one if you dont mind, you can track the progress in the linked ones.

**Comment by nmichael44** [comment]
i enabled logging in VS and I see this in the log:
/opt/ghc/8.8.4/lib/ghc-8.8.4/settings: openFile: does not exist (No such file or directory)

so i guess it is the same issue as the other tickets you mentioned.

I created the symbolic link as you described in the other ticket and the problem was fixed.  Thank you.  I have closed the ticket.

**Comment by chenyulue** [comment]
Is this problem solved completely? On windows 10 with ghc-8.8.4, I failed to compile the hls from the source due to the failure of compiling `with-utf8` executable. @jneira 

And still I don't know how to create the symbolic link on windows.

Any way, to use the hlint, I have to install `haskell-linter` extension with `hlint` additionally. That's my workaround that works for me.

**Comment by jneira** [comment]
it still is not solved, but there are other issues about, the windows specific one is #615
Hopefully my recent pr #1225 will solve the issue for all os's
